### ISSUE TITLE
ReadMail operator need to handle FolderClosedException

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.mail#5]
When connected to a mail server, the server may disconnect when we are connected for too long.

The operator will get this exception:
javax.mail.FolderClosedException: \* BYE JavaMail Exception: java.io.IOException: Connection dropped by server?
    at com.sun.mail.imap.IMAPFolder.throwClosedException(IMAPFolder.java:2749)
    at com.sun.mail.imap.IMAPFolder.idle(IMAPFolder.java:2551)
    at com.sun.mail.imap.IMAPFolder.idle(IMAPFolder.java:2467)
    at com.ibm.streamsx.mail.ReadMail.produceTuples(ReadMail.java:216)
    at com.ibm.streamsx.mail.ReadMail.access$0(ReadMail.java:181)
    at com.ibm.streamsx.mail.ReadMail$1.run(ReadMail.java:146)
    at java.lang.Thread.run(Thread.java:785)
    at com.ibm.streams.operator.internal.runtime.OperatorThreadFactory$2.run(OperatorThreadFactory.java:137)

We should handle this exception and reconnect to the server.

**Comment by chanskw** [comment]
Fixed

**Comment by amasj2d** [comment]
Hi @chanskw, I want to know how did you fixe this error!please I realy need this solution

**Comment by chanskw** [comment]
@amasj2d please see this around line 216:
https://github.com/IBMStreams/streamsx.mail/blob/master/com.ibm.streamsx.mail/impl/java/src/com/ibm/streamsx/mail/ReadMail.java

I caught the exception and reconnect after waiting for a period of time.

**Comment by amasj2d** [comment]
@chanskw many thanks for your quick answer, I'll see that and I'll give you a feedbaack. :)

**Comment by AnandKothalanka** [comment]
@chanskw I guess calling the same method again in catch block for every FolderClosedException will result in OutOfMemoryError as the catch block never completes..Please Correct me if i am wrong.

**Comment by AnandKothalanka** [comment]
I mean calling produceTuples() again and again
